Feature/epos4 support
ipa320/ipa_epos_hardware pull request #1
Opened 2017-07-31 09:01 UTC by ipa-jba

2017-08-01 08:44 UTC, ipa-fez requested changes

2017-08-01 08:44 UTC, ipa-fez commented on epos_hardware/install_udev_rules
> +sudo cp `rospack find epos_hardware`/rules/99-ftdi.rules /etc/udev/rules.d
these are both `99`, do you want to differentiate the numbers to make the order explicit?

2017-08-01 08:44 UTC, ipa-fez commented on epos_hardware/src/tools/list_devices.cpp
>  	BOOST_FOREACH(const std::string& protocol_stack_name, protocol_stack_names) {
No `c++11` available?

2017-08-01 08:44 UTC, ipa-fez commented on epos_hardware/src/util/epos.cpp
> +  } while (true)
Man, all these macros are pretty ugly...

2017-08-01 08:44 UTC, ipa-fez commented on epos_hardware/src/util/epos.cpp
> +  // }
delete?

2017-08-01 08:44 UTC, ipa-fez commented on epos_hardware/src/util/epos.cpp
>    }
I like all these extra scopes, why not break all these blocks out into functions?

2017-08-01 08:44 UTC, ipa-fez commented on epos_hardware/src/util/epos.cpp
> +    }
Duplicate code, also I think there's a `boost::clamp` or something...

2017-08-01 09:40 UTC, ipa-jba commented
I will integrate some of your comments. however I will not start a major rework (scopes,macros, ...) Many changes are due to formatting

2017-08-01 11:20 UTC, benmaidel requested changes

2017-08-01 11:20 UTC, ipa-bnm commented on epos_hardware/src/util/epos.cpp
> +                           << "Motor";
Why did you put this to a new line?

2017-08-01 11:20 UTC, ipa-bnm commented on epos_hardware/src/util/epos.cpp
> +                                  << "Motor Output";
Why did you put this to a new line?

2017-08-01 11:20 UTC, ipa-bnm commented on epos_library/include/epos_library/Definitions.h
> +	HelpFunctions_DllExport int  VCS_GetVersion(void* KeyHandle, unsigned short NodeId, unsigned short* pHardwareVersion, unsigned short* pSoftwareVersion, unsigned short* pApplicationNumber, unsigned s
Tab vs. Spaces

2017-08-01 11:20 UTC, ipa-bnm commented on epos_library/include/epos_library/Definitions.h
> +	HelpFunctions_DllExport int  VCS_ResetPortNameSelection(char* DeviceName, char* ProtocolStackName, char* InterfaceName, DWORD* pErrorCode);
Tab vs. Spaces

2017-08-01 11:20 UTC, ipa-bnm commented on epos_library/include/epos_library/Definitions.h
> +	Configuration_DllExport int  VCS_SetSsiAbsEncoderParameterEx(void* KeyHandle, unsigned short NodeId, unsigned short DataRate, unsigned short NbOfMultiTurnDataBits, unsigned short NbOfSingleTurnDataB
Tab vs. Spaces

2017-08-01 11:28 UTC, benmaidel requested changes
It would be better to split coding style changes from functional changes. It is hard to find the important changes.

As this code is mainly copied from somewhere, would't it make sense to just write a specialization for the epos class?

2017-08-01 12:13 UTC, ipa-jba commented
close here. restyling first, then I add new functionalities later

2017-08-01 12:23 UTC, ipa-jba commented on epos_library/include/epos_library/Definitions.h
> +	HelpFunctions_DllExport int  VCS_GetVersion(void* KeyHandle, unsigned short NodeId, unsigned short* pHardwareVersion, unsigned short* pSoftwareVersion, unsigned short* pApplicationNumber, unsigned s
this is shit. kudos maxon for messing up

2017-08-01 12:31 UTC, ipa-jba commented
I'm really in a state of "fuck this" with this repository. I did some changes needed for the hardware (because right now the only CAN interface is :hankey: and only "works" on the nvidia jetson) -> find a library -> use the library. I updated the  `epos_library` part to a version where EPOS4 Hardware runs, ran into trouble with units (tick/s vs rad/s). I think the changes should be documented (like I anticipated with this PR) but are somehow breaking for the original Interface from river-labs, but will be obsolete once CAN works.

Again. I agree with all of the comments/change requests, but will not fix existing code. I messed up (fixed) the messed up formatting for one file. Sorry about that (just review with `?w=1´)

2017-08-01 12:39 UTC, ipa-fez commented
@ipa-jba what's your comment about the `udev` stuff?

Resolve that and delete the big chunk of commented out code and it's OK for me...

2017-08-01 12:44 UTC, ipa-jba commented
@ipa-fez I'm on it (clamping as well :smile: )
The next pr will restyle the :hankey: out of here

2017-08-01 12:54 UTC, ipa-fez approved these changes

2017-08-04 09:28 UTC, ipa-bnm commented on epos_library/include/epos_library/Definitions.h
> +	HelpFunctions_DllExport int  VCS_GetVersion(void* KeyHandle, unsigned short NodeId, unsigned short* pHardwareVersion, unsigned short* pSoftwareVersion, unsigned short* pApplicationNumber, unsigned s
?

2017-08-04 09:34 UTC, ipa-jba commented on epos_library/include/epos_library/Definitions.h
> +	HelpFunctions_DllExport int  VCS_GetVersion(void* KeyHandle, unsigned short NodeId, unsigned short* pHardwareVersion, unsigned short* pSoftwareVersion, unsigned short* pApplicationNumber, unsigned s
the whole Definitions.h file is copied from the official library releasey by maxonmotor. I did not do any modifications -> I don't feel responsible or even see the need to style this --> thanks to maxonmotor for messing up the style and me receiving the blame. 

See https://www.maxonmotor.de/medias/sys_master/root/8825412976670/EPOS-Linux-Library-En.zip

2017-08-04 09:34 UTC, ipa-bnm commented
Man I've never seen so many :hankey: 's in one PR :)
Eat that :hankey: and get your approve

2017-08-04 09:34 UTC, benmaidel approved these changes

2017-08-04 09:40 UTC, merged